### PR TITLE
Foundation structure for searching feature 

### PR DESCRIPTION
**Pull request by ujithaperera**
Here I moved typeahead action body to separate service class. To keep search controller simple and readable, hope to move all other bulky search queries to the service class and optimise them within search_service class.

For JSON responses I selected json jbuilder. For the first step I create index.json.jbuilder to respond json requests. I found that this gem makes our REST calls simple.

Hope to continue on this foundation with your approval.

Thanks

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, just curious what your testing plans are for this code. Thanks!

**Comment by david-days** [comment]
For the UI portion, I'm going to run through and find some testable manual
runs on both the original plots2 code and the search code that we're
working on. (I have both as runnable setups on my dev laptop, both for
bringing in any updates from the master while we work and to perform these
kinds of tests).

The minimum requirement will be that the searches performed in both will
result in the same output at a minimum--if the code that Ujitha and I are
working on can produce more or more finely-tuned results, then it should be
good.  This will be the baseline for the first phase, and these test cases
will continue to be used to verify that we haven't irrevocably broken the
search code.

Once we get the RESTful endpoints up, I was planning on setting up one or
more test clients (bash & curl/wget, C#, Java, Python, or even a ruby
client) to start running automated calls and start benchmarking the
performance and wait times.  Since, at this point, we will be beyond the
original capabilities, the test cases and benchmarks will have to be
figured out as we go.  However, we can still run comparisons against the
original code by submitting equivalent calls to the standard typeahead and
search form submission processes.

That, as of now, is the overall plan.  It's a little seat-of-the-pants, but
we're going to be experimenting with the UI and javascript capabilities,
also, so it's not set in stone at the moment.

David

**Comment by jywarren** [comment]
I had an idea -- what if you created the tests and submitted them as a PR to the publiclab/plots2 master branch, and then they'd serve as the API for anyone working on any derived branch to work towards. That way, although you're not regularly rebasing and merging onto publiclab/plots2 master, there is a shared test suite for the search API that both must respect. 

That could potentially make the later (larger) rebase and merge back in smoother. Thoughts?

**Comment by david-days** [comment]
I think that is a fine idea.  After my last response, I was wondering if
you might want to keep these tool sets or not.

I will make an appropriate set of scripts and tools that can be used for
testing and benchmarking performance.  Probably stick to basic Linux tools
and software, unless I decide to get fancy.  (Wonder if there is any
utility in having a chrome extension to do this work?)
On Jun 3, 2016 9:30 PM, "Jeffrey Warren" <notifications@github.com> wrote:

I had an idea -- what if you created the tests and submitted them as a PR
to the publiclab/plots2 master branch, and then they'd serve as the API for
anyone working on any derived branch to work towards. That way, although
you're not regularly rebasing and merging onto publiclab/plots2 master,
there is a shared test suite for the search API that both must respect.

That could potentially make the later (larger) rebase and merge back in
smoother. Thoughts?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/david-days/plots2/pull/1#issuecomment-223728366>, or mute
the thread
<https://github.com/notifications/unsubscribe/AOOfYGpfvPPOeA17IavKby6IDdQJ5IpZks5qINU1gaJpZM4Itnk2>
.

**Comment by jywarren** [comment]
Cool - I think a first step might be to simply ensure that there are good
unit and functional tests for the search controller as it is now, as part
of the existing test suite. I think most search code is at the controller
level, so that could be a starting point.

**Comment by jywarren** [comment]
Ah, but the move to a search class is something I hadn't factored in here.
Moving to ujithas email now!

**Pull request merged**
