### PR TITLE
Completed RESTful search process

### PR DESCRIPTION
**Pull request by ujithaperera**
@david-days please review all the changes that I have made so far. Then we can update sqlite development and send PR to the upstream. 

cheers,
Ujitha.

### CODE REVIEW

**Comment by ujithaperera** [comment]
@david-days  all the tests are passed in my local.

**Comment by david-days** [comment]
I'm looking over the changes now.  Can't wait to get it all put together!

**Comment by david-days** [comment]
Sorry for the delay, Ujitha.  The changes look good, and I've pulled them in.

I've been working over the last 5 days trying to get the basics of the Grape and Swagger running.  It's actually starting to come together, but I might hit you up in the next day or two for some Rails advice--then we should be ready to start putting these two efforts together.

**Comment by ujithaperera** [comment]
Sure. I'm looking forward to work with you too. It's going to be a great experience. 
cheers !

**Pull request merged**
