### PR TITLE
Convert existed search function to resource-based search

### PR DESCRIPTION
**Pull request by ujithaperera**
Created search model
Moved possible search queries to search_service
Created additional views such as searches/new, searches/show

Several styles issues and optimisations are remaining.....

### CODE REVIEW

**Comment by david-days** [comment]
I'll check out the changes and pull them in.  You've been busy!

**Comment by jywarren** [comment]
Hmm, it's hard to see what the new search code is vs. the other changes from other contributors. Is it possible to bring the master branch up to 052a783 so that the proposed PR is only the diff between that and the latest (	6ae5acc)? Just a suggestion.

**Comment by david-days** [comment]
I can do that--I've got to get to a meeting, so it might be a couple of
hours.  Do you need me to do this early, or take a pass for the week?

**Comment by david-days** [comment]
Nope--merged with no conflicts on our end.  I still need to pull upstream changes when I get back, which might help you figure out any potential difficulties.

**Comment by jywarren** [comment]
all good, just a suggestion!

Cool. Just curious, are you rebasing changes to keep a linear commit
history? I've been doing that, as some people prefer it. Thanks!

**Comment by david-days** [comment]
I THINK that I have been doing that--I have experience with git, but it's
been on a much smaller basis.  Complete forks of other's code is generally
new to me.

I've been following github's guides as far as keeping forks up to date,
which includes rebasing, and that appeared to be the best way to manage
this from the perspective of minimizing the final merge.  Unless I've been
doing it severely wrong, then we (you, Ujitha, and I) should be able to
work the final submission together to make sure it goes smoothly.

**Comment by jywarren** [comment]
super!

**Comment by ujithaperera** [comment]
Actually I usually pull new updates from the upstream before continue with my branch, I think that's why all other contributor's commits also appear here.

**Pull request merged**
